// Code generated by protoc-gen-zig

const std = @import("std");
const mem = std.mem;
const Allocator = mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const FieldDescriptor = protobuf.FieldDescriptor;
const pb_decode = protobuf.pb_decode;
const pb_encode = protobuf.pb_encode;
const pb_deinit = protobuf.pb_deinit;
const pb_init = protobuf.pb_init;
const fd = protobuf.fd;

pub const Varints = struct {
    sint32: ?i32,
    sint64: ?i64,
    uint32: ?u32,
    uint64: ?u64,
    a_bool: ?bool,

    pub const _desc_table = .{
        .sint32 = fd(1, .{ .Varint = .ZigZagOptimized }),
        .sint64 = fd(2, .{ .Varint = .ZigZagOptimized }),
        .uint32 = fd(3, .{ .Varint = .Simple }),
        .uint64 = fd(4, .{ .Varint = .Simple }),
        .a_bool = fd(5, .{ .Varint = .Simple }),
    };

    pub fn encode(self: Varints, allocator: Allocator) ![]u8 {
        return pb_encode(self, allocator);
    }

    pub fn decode(input: []const u8, allocator: Allocator) !Varints {
        return pb_decode(Varints, input, allocator);
    }

    pub fn init(allocator: Allocator) Varints {
        return pb_init(Varints, allocator);
    }

    pub fn deinit(self: Varints) void {
        return pb_deinit(self);
    }
};
