// Code generated by protoc-gen-zig
///! package google.protobuf.compiler
const std = @import("std");
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;

const protobuf = @import("protobuf");
const ManagedString = protobuf.ManagedString;
const fd = protobuf.fd;
/// import package google.protobuf
const google_protobuf = @import("../protobuf.pb.zig");

pub const Version = struct {
    major: ?i32,
    minor: ?i32,
    patch: ?i32,
    suffix: ?ManagedString,

    pub const _desc_table = .{
        .major = fd(1, .{ .Varint = .Simple }),
        .minor = fd(2, .{ .Varint = .Simple }),
        .patch = fd(3, .{ .Varint = .Simple }),
        .suffix = fd(4, .String),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CodeGeneratorRequest = struct {
    file_to_generate: ArrayList(ManagedString),
    parameter: ?ManagedString,
    proto_file: ArrayList(google_protobuf.FileDescriptorProto),
    compiler_version: ?Version,

    pub const _desc_table = .{
        .file_to_generate = fd(1, .{ .List = .String }),
        .parameter = fd(2, .String),
        .proto_file = fd(15, .{ .List = .{ .SubMessage = {} } }),
        .compiler_version = fd(3, .{ .SubMessage = {} }),
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};

pub const CodeGeneratorResponse = struct {
    @"error": ?ManagedString,
    supported_features: ?u64,
    file: ArrayList(File),

    pub const _desc_table = .{
        .@"error" = fd(1, .String),
        .supported_features = fd(2, .{ .Varint = .Simple }),
        .file = fd(15, .{ .List = .{ .SubMessage = {} } }),
    };

    pub const Feature = enum(i32) {
        FEATURE_NONE = 0,
        FEATURE_PROTO3_OPTIONAL = 1,
        _,
    };

    pub const File = struct {
        name: ?ManagedString,
        insertion_point: ?ManagedString,
        content: ?ManagedString,
        generated_code_info: ?google_protobuf.GeneratedCodeInfo,

        pub const _desc_table = .{
            .name = fd(1, .String),
            .insertion_point = fd(2, .String),
            .content = fd(15, .String),
            .generated_code_info = fd(16, .{ .SubMessage = {} }),
        };

        pub usingnamespace protobuf.MessageMixins(@This());
    };

    pub usingnamespace protobuf.MessageMixins(@This());
};
